language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.5.1"
  - "3.5.2"
  - "3.5.3"
  - "3.5.4"
  - "3.5.5"
  - "3.6"
  - "3.6-dev"
  - "3.6.1"
  - "3.6.2"
  - "3.6.3"
  - "3.6.4"
  - "3.6.5"
  - "3.7-dev"
install:
  - "true"
script:
  - ./py/lambda_function.py
